APP_SECURITY_KEY = ''

PASSWORD = ""

FILENAME_SPLITTER = "<<-->>"

TEMP_FOLDER = "temp"
UPLOAD_FOLDER = f'{TEMP_FOLDER}/uploads'
OUTPUT_FOLDER = f'{TEMP_FOLDER}/output'
ZIP_FOLDER = f'{TEMP_FOLDER}/zipped'

FOLDERS = [TEMP_FOLDER, UPLOAD_FOLDER, OUTPUT_FOLDER, ZIP_FOLDER]
